"""service name should not be unique

Revision ID: 3dfb91ee6f30
Revises: a806bd7c5a81
Create Date: 2024-08-29 16:07:51.066776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dfb91ee6f30'
down_revision: Union[str, None] = 'a806bd7c5a81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_service_service_name', table_name='service')
    op.create_index(op.f('ix_service_service_name'), 'service', ['service_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_service_name'), table_name='service')
    op.create_index('ix_service_service_name', 'service', ['service_name'], unique=1)
    # ### end Alembic commands ###
