"""Initial migration

Revision ID: a806bd7c5a81
Revises: 
Create Date: 2024-08-20 11:02:47.272818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a806bd7c5a81'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ip', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id_server', sa.Integer(), nullable=False),
    sa.Column('keyfilename', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id_server')
    )
    op.create_index(op.f('ix_server_name'), 'server', ['name'], unique=True)
    op.create_table('service',
    sa.Column('id_server', sa.Integer(), nullable=True),
    sa.Column('service_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id_service', sa.Integer(), nullable=False),
    sa.Column('service_type', sa.Enum('ONLINE', 'JOURNAL', 'SYSTEMD', name='servicetypeenum'), nullable=False),
    sa.ForeignKeyConstraint(['id_server'], ['server.id_server'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_service')
    )
    op.create_index(op.f('ix_service_service_name'), 'service', ['service_name'], unique=True)
    op.create_index(op.f('ix_service_service_type'), 'service', ['service_type'], unique=False)
    op.create_table('beat',
    sa.Column('id_service', sa.Integer(), nullable=False),
    sa.Column('Active', sa.Boolean(), nullable=False),
    sa.Column('latency', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.Column('server_status', sa.Boolean(), nullable=False),
    sa.Column('id_beat', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_service'], ['service.id_service'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_beat')
    )
    op.create_index(op.f('ix_beat_id_service'), 'beat', ['id_service'], unique=False)
    op.create_table('config',
    sa.Column('interval', sa.Float(), nullable=False),
    sa.Column('id_service', sa.Integer(), nullable=True),
    sa.Column('method', sa.Enum('POST', 'GET', name='methodenum'), nullable=True),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('desired_response', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('operator', sa.Enum('IN', 'NOTIN', 'EQ', 'NE', name='onlineoperatorenaum'), nullable=True),
    sa.Column('target', sa.Enum('STATUS', 'CONTENT', name='targetenaum'), nullable=True),
    sa.Column('data', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id_config', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_service'], ['service.id_service'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_config')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('config')
    op.drop_index(op.f('ix_beat_id_service'), table_name='beat')
    op.drop_table('beat')
    op.drop_index(op.f('ix_service_service_type'), table_name='service')
    op.drop_index(op.f('ix_service_service_name'), table_name='service')
    op.drop_table('service')
    op.drop_index(op.f('ix_server_name'), table_name='server')
    op.drop_table('server')
    # ### end Alembic commands ###
