name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:

  build:


    runs-on: ubuntu-latest

    env:
      PYTHONPATH: ${{ github.workspace }}
    

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    
    - name: Install Redis
      run: |
        sudo apt-get update
        sudo apt-get install redis-server -y
      
    - name: Start Redis server
      run: |
        sudo service redis-server start
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
    - name: Test with pytest
      run: |
        pytest
