name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:

  build:


    runs-on: ubuntu-latest

    env:
      PYTHONPATH: ${{ github.workspace }}
    

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    
    - name: Install apt dependencies
      run: |
        apt install libkrb5-dev
        apt install python3.12-dev
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f back/requirements.txt ]; then pip install -r back/requirements.txt; fi
          
    - name: Test with pytest
      run: |
        cd back; pytest
